# Generated by Django 5.1.2 on 2024-10-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titles',
            new_name='title',
        ),
    ]
